version: '3'

networks:
  petprojects:
    driver: bridge

volumes:
  db:

services:
  amateur-tournament-tennis-tg-db:
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "${DOCKER_DB_PORT?err}:3306"
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Europe/Moscow
    volumes:
      - db:/var/lib/mysql
      - ./tmp:/var/tmp:rw
    networks:
      - petprojects

  amateur-tournament-tennis-tg:
    platform: linux/arm64
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    ports:
      - "8083:8000"
    depends_on:
      - amateur-tournament-tennis-tg-db
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/site.conf
      - ./:/var/www/project
      - ./log:/var/www/log
    networks:
      petprojects:
        aliases:
          - "${HOST_AMATEUR_TOURNAMENT?err}"
        
